locale: en-us
title: Functions & Glory
subtitle: sharing some stuff i think i know;
name: FG
description: sharing some stuff i think i know;
url: https://functionsandglory.github.io
baseurl: /
repository: functionsandglory/functionsandglory.github.io
logo: /assets/site/fg-badge-logo.png
author:
  name: F.G.
  avatar: /assets/site/fg-avatar.png
  bio: Principal Software Engineer / Startup in CA
  location: California, USA
  links:
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: https://twitter.com/funcsandglory
    - label: GitHub
      icon: fab fa-fw fa-github-square
      url: https://github.com/functionsandglory
    - label: Email
      icon: fas fa-fw fa-envelope-square
      url: mailto:functionsandglory@proton.me
twitter:
  username: funcsandglory
og_image: /images/fg-badge-logo.png
comments:
  provider: disqus
  disqus:
    shortname: functionsandglory
social:
  name:  F.G.
  links:
    - https://twitter.com/funcsandglory
    - https://github.com/functionsandglory
analytics:
  provider: google-gtag
  google:
    tracking_id: G-XGHWEETRM7
minimal_mistakes_skin: dark
defaults:
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      comments: false
      read_time: true
      share: false

# Build settings
include: [_pages]
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-include-cache
  - jekyll-feed
