google_measurement_id: G-XGHWEETRM7

# site
locale: en-us
title: Functions & Glory
subtitle: sharing some stuff i think i know;
name: F.G.
description: sharing some stuff i think i know;
url: https://functionsandglory.github.io
baseurl: /
repository: functionsandglory/functionsandglory.github.io
logo: /images/fg-badge-logo.png
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true

# theme
minimal_mistakes_skin: dark

footer_links:
  - title: Twitter
    url: https://twitter.com/FuncsAndGlory
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/functionsandglory
    icon: fab fa-github-square
  - title: Email
    url: mailto:functionsandglory@proton.me
    icon: fas fa-envelope-square

# Build settings
include: ["_pages"]
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-include-cache
